# Generated by Django 2.2.3 on 2019-07-10 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0004_auto_20190710_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=255)),
                ('nameAr', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameAr', models.CharField(max_length=255)),
                ('nameEn', models.CharField(max_length=255)),
                ('code', models.CharField(default='', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AbstractProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameEn', models.CharField(max_length=255)),
                ('nameAr', models.CharField(max_length=255)),
                ('descriptionAr', models.TextField(default='')),
                ('descriptionEn', models.TextField(default='')),
                ('code', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('gender', models.CharField(choices=[(0, 'Female'), (1, 'Male')], max_length=10)),
                ('status', models.CharField(choices=[(0, 'unavailable'), (1, 'available')], max_length=10)),
                ('createdAt', models.DateTimeField(auto_now=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Grade')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.Media')),
            ],
        ),
    ]
