# Generated by Django 2.2.3 on 2019-07-11 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190710_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('abstractProduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.AbstractProduct')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Size')),
            ],
        ),
    ]
