# Generated by Django 2.2.3 on 2019-07-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('size', 'abstractProduct')},
        ),
    ]
