# Generated by Django 2.2.3 on 2019-07-11 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190711_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='abstractProduct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.AbstractProduct'),
        ),
    ]
