# Generated by Django 2.2.3 on 2019-07-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20190711_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproduct',
            name='code',
        ),
        migrations.RemoveField(
            model_name='abstractproduct',
            name='price',
        ),
        migrations.RemoveField(
            model_name='abstractproduct',
            name='status',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available')], default='', max_length=20),
            preserve_default=False,
        ),
    ]
