# Generated by Django 2.2.3 on 2019-07-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190714_1734'),
        ('product', '0006_auto_20190718_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstractproduct',
            name='image',
        ),
        migrations.AddField(
            model_name='abstractproduct',
            name='images',
            field=models.ManyToManyField(to='media.Media'),
        ),
    ]
