# Generated by Django 2.2.3 on 2019-07-30 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190721_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='code',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
