# Generated by Django 2.2.3 on 2019-08-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190801_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='code',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
