# Generated by Django 2.2.3 on 2019-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_grade_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available')], default='available', max_length=20),
        ),
    ]
