# Generated by Django 2.2.3 on 2019-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190805_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractproduct',
            name='status',
            field=models.CharField(choices=[('unavailable', 'unavailable'), ('available', 'available')], default='available', max_length=20),
        ),
    ]
