# Generated by Django 2.2.3 on 2019-07-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20190709_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
