# Generated by Django 2.2.3 on 2019-07-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20190709_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
