# Generated by Django 2.2.3 on 2019-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
