# Generated by Django 2.2.3 on 2019-07-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('state', '0001_initial'),
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='states',
            field=models.ManyToManyField(related_name='centers', to='state.State'),
        ),
    ]
