# Generated by Django 2.2.3 on 2019-07-28 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0002_center_states'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated')], default='activated', max_length=100),
        ),
    ]
