# Generated by Django 2.2.3 on 2019-07-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190721_1259'),
        ('center', '0003_center_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CenterProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.Center')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
        migrations.AddField(
            model_name='center',
            name='products',
            field=models.ManyToManyField(related_name='centers', through='center.CenterProduct', to='product.Product'),
        ),
    ]
