# Generated by Django 2.2.3 on 2019-07-30 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20190730_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='centerproduct',
            old_name='stock',
            new_name='count',
        ),
    ]
