# Generated by Django 2.2.3 on 2019-07-30 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20190730_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='centerproduct',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
