# Generated by Django 2.2.3 on 2019-07-30 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190721_1259'),
        ('center', '0006_centerproduct_createdat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='center',
            name='products',
        ),
        migrations.AlterField(
            model_name='centerproduct',
            name='center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='center.Center'),
        ),
        migrations.AlterUniqueTogether(
            name='centerproduct',
            unique_together={('center', 'product')},
        ),
    ]
