# Generated by Django 2.2.3 on 2019-07-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190718_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('activated', 'activated'), ('deactivated', 'deactivated')], default='activated', max_length=100),
        ),
    ]
