# Generated by Django 2.2.3 on 2019-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
    ]
