# Generated by Django 2.2.3 on 2019-07-30 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_auto_20190730_0941'),
        ('user', '0012_auto_20190729_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='center.Center'),
        ),
    ]
