# Generated by Django 2.2.3 on 2019-07-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=250)),
                ('path', models.CharField(max_length=250)),
            ],
        ),
    ]
