# Generated by Django 2.2.3 on 2019-07-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
