# Generated by Django 2.2.3 on 2019-07-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_media_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='file',
            field=models.FileField(default='dsd', upload_to='../medias/'),
            preserve_default=False,
        ),
    ]
