# Generated by Django 2.2.3 on 2019-07-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='path',
        ),
        migrations.RemoveField(
            model_name='media',
            name='type',
        ),
        migrations.RemoveField(
            model_name='media',
            name='url',
        ),
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='../static'),
        ),
    ]
