# Generated by Django 2.2.3 on 2019-07-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20190710_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='../media'),
        ),
    ]
