# Generated by Django 2.2.3 on 2019-07-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='name',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
