# Generated by Django 2.2.3 on 2019-07-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20190713_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='createdAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
