# Generated by Django 2.2.3 on 2019-07-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190714_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
