# Generated by Django 2.2.3 on 2019-07-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20190717_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('canceled', 'canceled'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
