# Generated by Django 2.2.3 on 2019-07-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20190718_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assignedAt',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='canceledAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveredAt',
            field=models.DateTimeField(null=True),
        ),
    ]
