# Generated by Django 2.2.3 on 2019-07-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20190718_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assignedAt',
            field=models.DateTimeField(null=True),
        ),
    ]
