# Generated by Django 2.2.3 on 2019-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20190718_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('canceled', 'canceled'), ('inDelivery', 'inDelivery'), ('packed', 'packed'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
