# Generated by Django 2.2.3 on 2019-07-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_auto_20190729_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliveringAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='packedAt',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('assigned', 'assigned'), ('canceled', 'canceled'), ('delivering', 'delivering'), ('packed', 'packed'), ('delivered', 'delivered')], default='pending', max_length=20),
        ),
    ]
