# Generated by Django 2.2.3 on 2019-07-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_auto_20190729_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='isDelivery',
            field=models.BooleanField(default=True),
        ),
    ]
